# Generated by Django 5.2.1 on 2025-05-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('smartphones', 'smartphones'), ('laptops', 'laptops'), ('accessories', 'accessories')], max_length=100, null=True),
        ),
    ]
