# Generated by Django 5.2.1 on 2025-05-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(choices=[('Space Black', 'Space Black'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('White', 'White')], default='Space Black', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_key_features',
            field=models.TextField(help_text='Separate each feature with a semicolon (;)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('smartphones', 'smartphones'), ('laptops', 'laptops'), ('accessories', 'accessories')], default='smartphones', max_length=100, null=True),
        ),
    ]
