# Generated by Django 5.2.1 on 2025-05-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_available_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('smartphones', 'smartphones'), ('laptops', 'laptops'), ('accessories', 'accessories')], max_length=100, null=True),
        ),
    ]
