# Generated by Django 5.2.1 on 2025-05-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, to='products.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_storage',
            field=models.ManyToManyField(blank=True, to='products.storage'),
        ),
    ]
